# NUMPY

In [1]:
import numpy as np

## Numpy Array

* Numpy arrayları python listlere benziyor

* ama onların aksine, farklı veri tiplerinde elemanlar içermez. Tek veri tipinde elemanlar olması gerekiyor.

## Listlerden Array Yaratmak

In [2]:
x = np.array([1,2,3,4])

In [3]:
x

array([1, 2, 3, 4])

In [4]:
type(x)

numpy.ndarray

In [5]:
y = np.array(["a","b","c"])

In [6]:
y

array(['a', 'b', 'c'], dtype='<U1')

In [7]:
type(y)

numpy.ndarray

In [10]:
# bütün integerlar stringe dönüştürülecek
z=np.array([1,2,3,"a"])

In [11]:
z

array(['1', '2', '3', 'a'], dtype='<U21')

In [13]:
a=np.array([1,2,3,"5"])

In [14]:
a

array(['1', '2', '3', '5'], dtype='<U21')

In [15]:
# bütün integerlar float a dönüştürülecek
b=np.array([1,2,3,4.5])

In [16]:
b

array([1. , 2. , 3. , 4.5])

In [18]:
# bütün integerlar ve floatlar stringe dönüşecek
c=np.array([1,2,3,4.5,"6"])

In [19]:
c

array(['1', '2', '3', '4.5', '6'], dtype='<U32')

## Array Data Tipini Manuel Belitmek

* array'in elemanlarının tiğinin ne olacağını özellikle belirtebiliriz.

In [20]:
x = np.array([1,2,3,4.6])

In [21]:
x

array([1. , 2. , 3. , 4.6])

In [22]:
x = np.array([1,2,3,4.6],dtype = "int32")

In [23]:
x

array([1, 2, 3, 4], dtype=int32)

In [24]:
x = np.array([1,2,3,4.6],dtype = "str")

In [25]:
x

array(['1', '2', '3', '4.6'], dtype='<U3')

In [26]:
x=np.array(["4.2"],dtype="int32")

ValueError: invalid literal for int() with base 10: '4.2'

## Elemanları 0'lardan Oluşan Array Oluşturmak

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros(10,dtype="str")

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

### Elemanları 0'lardan Oluşan Multidimensional Array Oluşturmak

In [32]:
 # 3 row(Satır) ve 4column(sütun)'u olan bir array oluşturmak
    
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.zeros([3,4,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### Belirtilen Bir Elemandan Array Oluşturmak

In [35]:
np.full((4,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [36]:
np.full(4,5,5)

TypeError: Cannot interpret '5' as a data type

In [37]:
np.full(4,5)

array([5, 5, 5, 5])

In [38]:
np.full((4,5),"a")

array([['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a']], dtype='<U1')

In [39]:
np.full((4,5),5.2)

array([[5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2]])

In [40]:
np.full((4,5),5.2,dtype="str")

array([['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5']], dtype='<U1')

In [41]:
np.full((4,5),"5.2")

array([['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2']], dtype='<U3')

## Ardaşık sayılardan Array Oluşturmak

In [43]:
# [0,12)
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [46]:
np.arange(2,12,-2)

array([], dtype=int64)

In [47]:
np.arange(12,2,-2)

array([12, 10,  8,  6,  4])

## Aralığı Eşit Uzaklıktaki Noktalara Bölmek

In [48]:
# Default olarak 50 nokta döndürür
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

### Kaç Parçaya Böleceğini Belirtmek

In [49]:
np.linspace(1,2,num=3)

array([1. , 1.5, 2. ])

In [50]:
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [51]:
np.linspace(1,2,num=3,endpoint=False)

array([1.        , 1.33333333, 1.66666667])

In [52]:
# 0 ve 1 arasında (0-1 dahil olacak şekilde) 30 nokta üretmek
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [53]:
np.linspace(0.54,4.778,30)

array([0.54      , 0.68613793, 0.83227586, 0.97841379, 1.12455172,
       1.27068966, 1.41682759, 1.56296552, 1.70910345, 1.85524138,
       2.00137931, 2.14751724, 2.29365517, 2.4397931 , 2.58593103,
       2.73206897, 2.8782069 , 3.02434483, 3.17048276, 3.31662069,
       3.46275862, 3.60889655, 3.75503448, 3.90117241, 4.04731034,
       4.19344828, 4.33958621, 4.48572414, 4.63186207, 4.778     ])

## Normal Disribution'dan Çekilmiş Değerler İle Array Oluşturmak

* mean,std,array size

In [54]:
np.random.normal(0,1,(4,5))

array([[-0.36888964,  1.490958  ,  0.38152225, -1.68011695,  0.31711971],
       [ 0.27510821,  1.50362867, -0.85290499, -1.5322224 , -0.05730489],
       [-0.92016461, -0.47524607,  0.37013646,  1.27748285,  0.51287808],
       [ 0.48026414,  0.37857281, -0.606082  ,  0.65865578, -0.01098767]])

In [55]:
np.random.normal(0,100,(4,5))

array([[ 201.88650454,  -35.34232888,  -66.67818431,   63.4606258 ,
          74.14586677],
       [ -50.85372039,   79.85089129,  -12.18609325,  138.27053357,
         -63.7089324 ],
       [  73.68671753,   70.26292384,  112.23119275,  175.09476125,
           5.51681325],
       [ -76.6542649 ,  149.5976837 , -171.32831968,  -69.38934779,
         -39.03144869]])

In [56]:
np.random.normal(10,100,(4,5))

array([[ 181.39079382,   -0.47066564,  -44.08953065,   99.94122334,
          46.11242062],
       [ 297.71217292,   76.43337383,   19.19496258,  -84.85792287,
           9.44030684],
       [ -55.70969728,  -64.90654331,   96.08095366,   92.85009522,
          98.64754044],
       [  75.86190824,  190.01590314,    0.30596546,  171.75505525,
        -138.52576161]])

In [57]:
np.random.normal(10,1,(4,5))

array([[ 9.95004281, 10.43027487,  9.26552107, 10.52279859, 10.29611091],
       [ 9.32508096,  9.79224583, 10.12482918,  9.97292272,  8.37285235],
       [ 9.24002441,  9.39499958, 10.04814134, 10.21633489, 10.43977837],
       [ 9.92493295,  9.28811131,  9.89707345,  9.75539804,  9.67975342]])

### Random Inreger'lar ile Array Oluşturmak

* (low,high)

In [59]:
np.random.randint(1,10,(3,4))

array([[4, 7, 8, 2],
       [4, 3, 7, 8],
       [1, 3, 3, 7]])

In [60]:
np.random.randint(1,10,(3,5,5))

array([[[8, 4, 1, 6, 6],
        [6, 9, 1, 4, 8],
        [9, 4, 2, 1, 4],
        [4, 9, 1, 7, 4],
        [1, 4, 4, 3, 8]],

       [[2, 4, 4, 4, 5],
        [7, 6, 4, 1, 1],
        [8, 5, 5, 5, 8],
        [7, 1, 3, 2, 8],
        [2, 5, 7, 6, 4]],

       [[2, 4, 9, 6, 5],
        [6, 6, 1, 8, 3],
        [5, 4, 5, 3, 6],
        [6, 1, 7, 5, 6],
        [8, 1, 8, 2, 8]]])

In [63]:
np.random.randint(1,5)

4

In [65]:
d = {}
for _ in range(2000):
    val=np.random.randint(1,11)
    
    if val not in d:
        d[val]=1
    else:
        d[val]+=1

In [66]:
d

{5: 169,
 10: 204,
 8: 216,
 1: 188,
 3: 199,
 2: 188,
 9: 226,
 6: 195,
 7: 200,
 4: 215}

## Identity (Birim) Matrix Oluşturmak

* [low,high]

In [67]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [68]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array İşlemleri

In [69]:
#   * operatörü iki list arasında tanımsızdır, hata verir.

a=[1,2,3]
b=[2,3,5]

a*b

TypeError: can't multiply sequence by non-int of type 'list'

* list ile integer çarpılırsa ard arda concatenation yapar


In [70]:
[2,3,5]*3

[2, 3, 5, 2, 3, 5, 2, 3, 5]

In [71]:
[2,3,5]+[1,2,3]

[2, 3, 5, 1, 2, 3]

*    * operatörü iki numpy arrayi arasında tanımlıdır, element-wise(eleman bazlı) çarpma yapar

In [73]:
x = np.array([1,2,3,])
y = np.array([2,4,8])

x*y

array([ 2,  8, 24])

* element-wise çarpım yaptığı için çarpılan iki array'ın sayısı aynı olmalı

In [74]:
x = np.array([1,2,3,])
y = np.array([2,4,8,4])

x*y

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [75]:
x = np.array([1,2,3,])
y = np.array([2,4,8])

x+y

array([ 3,  6, 11])

In [76]:
print(x)
print(y)

[1 2 3]
[2 4 8]


In [77]:
x+y

array([ 3,  6, 11])

In [78]:
a

[1, 2, 3]

In [79]:
3*a

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [80]:
x

array([1, 2, 3])

In [81]:
x*3

array([3, 6, 9])

In [82]:
x

array([1, 2, 3])

In [85]:
x=x*3

In [86]:
x

array([ 9, 18, 27])

## Array attribute'ları


### Shape

In [88]:
x = np.zeros([2,3])
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [89]:
y = np.zeros([2,5,4])
print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [90]:
x.shape

(2, 3)

In [91]:
y.shape

(2, 5, 4)

### ndim

In [92]:
x = np.zeros([2,3])
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [93]:
y = np.zeros([2,5,4])
print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [94]:
x.ndim


2

In [95]:
y.ndim

3

### Size

In [96]:
x = np.zeros([2,3])
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [97]:
y = np.zeros([2,5,4])
print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [98]:
x.size

6

In [99]:
y.size

40

### Dtype

In [100]:
x = np.zeros([2,3])
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [101]:
y = np.zeros([2,5,4])
print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [103]:
x.dtype

dtype('float64')

## Reshaping

* Önemli nokta reshape yapacağımız yapının yaptıkları sonraki yapıyla aynı elelmana sahip olması, yani sizelerı aynı olmalı

In [104]:
a=np.arange(1,11)

In [105]:
a.ndim

1

In [106]:
a.size

10

In [107]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [108]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [109]:
a.reshape(2,5).ndim

2

* eleman sayısı tutmazsa hata alırım


In [110]:
a.reshape(6,2)

ValueError: cannot reshape array of size 10 into shape (6,2)

### -1 ile Boyuta Karar Vermek

In [111]:
a.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### Yeni boyut Eklemek

In [123]:
a = np.arange(1,11)

In [124]:
a[np.newaxis,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [125]:
a[np.newaxis,:].shape

(1, 10)

In [126]:
# column vector

a[:,np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [127]:
a[np.newaxis,:].shape

(1, 10)

In [128]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

* Veya **None** olarak yazaibiliriz.

In [129]:
a[:,None]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

## Concatenation


In [130]:
a = np.array([1,2,3,4])

In [131]:
b = np.array([4,5,6,7])

In [132]:
np.concatenate([a,b])

array([1, 2, 3, 4, 4, 5, 6, 7])

* **Python listlerini de numpy arraylari ile concatenation'a sokabilriz.** 

In [133]:
l=[10,11]

In [134]:
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  4,  5,  6,  7, 10, 11])

In [135]:
l=[10,11,"11.11"]

In [136]:
# Hepsini stringe dönüştürüyor
np.concatenate([a,b,l])

array(['1', '2', '3', '4', '4', '5', '6', '7', '10', '11', '11.11'],
      dtype='<U21')

### Size Mismatch

In [137]:
a

array([1, 2, 3, 4])

In [139]:
x = np.array([[1, 2 ,3],
             [4,5,6]])

In [140]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [141]:
x.size

6

In [142]:
x.shape

(2, 3)

In [143]:
a.shape

(4,)

In [145]:
# shape mismatch
np.concatenate([x,a])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [146]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [147]:
np.concatenate([x,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [151]:
np.concatenate([x,x],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Stack

* Stack mantığı yeni dimension ekleyip o diemension üzerinden concatenation yaparak sağlayabiliriz.


### stack

In [153]:
a=np.array([1,2,3,4])

In [154]:
b=np.array([5,6,7,8])

In [155]:
a.shape

(4,)

In [156]:
b.shape

(4,)

In [157]:
np.stack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [158]:
np.stack([a,b],axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## Splitting

In [159]:
l = [ 10,20,30,40,50,60,70,80,90]

In [160]:
l

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [162]:
# [0,1],[2,3,4,5],[6,7,8,9]
np.split(l,[2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80, 90])]

In [163]:
np.split(l,[3,5])

[array([10, 20, 30]), array([40, 50]), array([60, 70, 80, 90])]

### Split'in Sonucunu Birden Çok Değişkene Eşitleme

In [164]:
a,b =(1,10)

In [169]:
print(a)
print(b)

1
10


In [170]:
x,y,z = np.split(l,[2,6])

In [171]:
print(x)
print(y)
print(z)

[10 20]
[30 40 50 60]
[70 80 90]


### vsplit

In [172]:
a=np.arange(20).reshape(2,10)

In [173]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [174]:
np.vsplit(a,[1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [175]:
np.vsplit(a,[1])[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### hsplit

In [176]:
a=np.arange(20).reshape(2,10)

In [177]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [178]:
np.hsplit(a,[2])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [179]:
np.hsplit(a,[2])[0]

array([[ 0,  1],
       [10, 11]])

In [180]:
np.hsplit(a,[2])[1]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [181]:
x,y = np.hsplit(a,[2])

In [182]:
print(x)
print(y)

[[ 0  1]
 [10 11]]
[[ 2  3  4  5  6  7  8  9]
 [12 13 14 15 16 17 18 19]]


In [186]:
a=np.arange(20).reshape(5,4) 
a1,a2,a3=np.vsplit(a,[2,3]) 

In [187]:
a2.shape

(1, 4)

## Shorting


In [188]:
a=np.array([10,25,65,54,21,10,1,3])

In [189]:
a

array([10, 25, 65, 54, 21, 10,  1,  3])

In [190]:
np.sort(a)

array([ 1,  3, 10, 10, 21, 25, 54, 65])

In [192]:
a

array([10, 25, 65, 54, 21, 10,  1,  3])

In [193]:
a.sort()

In [194]:
a

array([ 1,  3, 10, 10, 21, 25, 54, 65])

## argsort

In [195]:
a=np.array([10,25,65,54,21,10,1,3])

In [196]:
idxs=np.argsort(a)

In [197]:
idxs

array([6, 7, 0, 5, 4, 1, 3, 2])

# Multidimensional Arraylerin Elemanlarına Ulaşmak

In [200]:
a = np.arange(1,21).reshape(4,5)

In [201]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [202]:
a[0]

array([1, 2, 3, 4, 5])

In [203]:
a[1]

array([ 6,  7,  8,  9, 10])

In [204]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [205]:
a[0,0]

1

In [206]:
a[0][0]

1

In [207]:
a[1,1]

7

In [208]:
a.ndim

2

In [209]:
# array'in veri tiği neyse ona cast olur,array in veri tipi dönüştürülemez
a[1,1]=20.75

In [210]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 20,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### Slice Indexing

In [211]:
a = np.arange(1,21).reshape(4,5)

In [212]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [213]:
a[1]

array([ 6,  7,  8,  9, 10])

In [214]:
a[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [215]:
a[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [217]:
a[0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [218]:
a[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [219]:
# bütün rowları al ama sadece 3x indezteki column u al
a[:,3]

array([ 4,  9, 14, 19])

In [221]:
a[::2,3]

array([ 4, 14])

In [222]:
x=np.arange(1,13).reshape(3,4) 

In [223]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [224]:
x[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

## Fancy Indexing

In [225]:
x=np.arange(1,15)

In [226]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [227]:
idxs=[4,5,7,11]

In [228]:
# 4 ,5, 7 , 11. indexteki elemanalrı döndürür.
x[idxs]

array([ 5,  6,  8, 12])

In [229]:
x=np.arange(1,13).reshape(3,4) 

In [231]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [237]:
a[0:2,1]

array([2, 7])

In [234]:
a[0:2,1].shape

(2,)

In [241]:
a[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [242]:
a[0:2,1:3].shape

(2, 2)

In [243]:
x=np.arange(20).reshape(4,5) 

In [244]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [245]:
idx1=[1,3,2]

In [246]:
idx2=[3,0,2]

In [247]:
x[idx1,idx2]

array([ 8, 15, 12])

In [248]:
x[idx1,idx2].shape

(3,)

In [249]:
x[idx1][idx2]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [253]:
x[[1,2,0]]=55

In [254]:
x

array([[55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55],
       [15, 16, 17, 18, 19]])

## Subarray

In [255]:
x=np.arange(20).reshape(4,5) 

In [256]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [257]:
b=x[:2,:3]

In [258]:
b

array([[0, 1, 2],
       [5, 6, 7]])

In [259]:
b.ndim

2

In [261]:
b[0,0]=100

In [263]:
b

array([[100,   1,   2],
       [  5,   6,   7]])

In [264]:
x

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

### Copy

In [265]:
x=np.arange(20).reshape(4,5) 

In [266]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [270]:
b=x[:2,:3].copy()

In [271]:
b

array([[0, 1, 2],
       [5, 6, 7]])

In [272]:
b[0,0]=100

In [273]:
b

array([[100,   1,   2],
       [  5,   6,   7]])

In [274]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# Conditinal Indexing

In [276]:
a=np.arange(10)

In [277]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [278]:
a<5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [279]:
a[a<5]

array([0, 1, 2, 3, 4])

In [280]:
filt=a<3

In [281]:
a[filt]

array([0, 1, 2])

In [293]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [294]:
b=np.array([1,2,5,4,8,9,5,23,2,25,21,15,75,45])

In [295]:
b

array([ 1,  2,  5,  4,  8,  9,  5, 23,  2, 25, 21, 15, 75, 45])

In [297]:
a[a==b]

/tmp/ipykernel_11152/3270349921.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a[a==b]


array([], shape=(0, 10), dtype=int64)

In [298]:
(a<3)or(a>5)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [299]:
(a<3)|(a>5)

array([ True,  True,  True, False, False, False,  True,  True,  True,
        True])

In [300]:
a[(a<3)|(a>5)]

array([0, 1, 2, 6, 7, 8, 9])

In [301]:
filt=(a<3)|(a>5)

In [302]:
filt

array([ True,  True,  True, False, False, False,  True,  True,  True,
        True])

In [303]:
a[filt]

array([0, 1, 2, 6, 7, 8, 9])

### Filtrenin Değili

In [304]:
a=np.arange(1,21).reshape(4,5)

In [305]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [306]:
filt=a<5

In [307]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [308]:
~filt

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## SUM

* Verilen condition kaç elemanın sağladığını bulalım.

In [309]:
a=np.arange(1,21).reshape(4,5)

In [310]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [311]:
np.sum(a)

210

In [312]:
filt=a<5

In [313]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [314]:
np.sum(filt)

4

In [315]:
a[filt]

array([1, 2, 3, 4])

In [316]:
np.sum(a[filt])

10

## Belirli Axis Üzerinde Toplamak

In [324]:
np.sum(a,axis=0)

array([34, 38, 42, 46, 50])

In [325]:
np.sum(a,axis=1)

array([15, 40, 65, 90])

# All

* Tüm elemanlar verilen şartı sağlıyor mu?

In [326]:
a=np.arange(1,21).reshape(4,5)

In [327]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [328]:
a>-1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [329]:
np.all(a>-1)

True

In [330]:
np.all(a>5)

False

In [331]:
np.all(a>8,axis=1) 

array([False, False,  True,  True])

## Any()

* Herhangi bir eleman şartı sağlıyor mu?

In [332]:
a=np.arange(1,21).reshape(4,5)

In [333]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [334]:
a>17

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True,  True,  True]])

In [336]:
np.any(a>17)

True

In [337]:
np.any(a>17,axis=0)

array([False, False,  True,  True,  True])

In [338]:
np.any(a>17,axis=1)

array([False, False, False,  True])